spring:
    application:
        name: preparcial
    mustache:
        suffix: .html
    datasource:
        url: jdbc:postgresql://localhost:5432/clinica
        username: postgres
        password: 12345678Aa!
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                globally_quoted_identifiers: true
                jdbc:
                    batch_size: 20
                transaction:
                    flush_before_completion: true
    sql:
        init:
            mode: always


jwt:
    secret: "94c9b14f-b497-4f25-bc02-4f5e1a512c3d"
    exptime: 1296000000